### ISSUE TITLE
Your package breaks when defunct future::multiprocess will be removed

### ISSUE THREAD

**Issue by HenrikBengtsson** [twolodzko/kernelboot#10]
FYI, `future::multiprocess` has been deprecated since October 2020, and defunct since March 2023.  It will soon be removed from **future**.  When that happens, your package will break (see below).  Could you please fix this?  It's probably not used by your package anyway, since it's already defunct.  Thank you.

*   checking Rd cross-references ... WARNING
    ```
    Missing link or links in documentation object 'jst_import.Rd':
      ‘[future:multiprocess]{future::multiprocess()}’
    
    See section 'Cross-references' in the 'Writing R Extensions' manual.
    ```

**Comment by twolodzko** [comment]
@HenrikBengtsson Hi, I'm fairly certain this was already fixed last year https://github.com/twolodzko/kernelboot/commit/b6a821c77f6f1b4acc3a92c31bd1f43b904b9a2e , could you clarify?

**Comment by HenrikBengtsson** [comment]
It's still in the docs. See also my last comment in the previous issue.

**Comment by twolodzko** [comment]
Thanks. Fix is on CRAN.
