### ISSUE TITLE
TESTS: Wrong assertion when availableCores() == 1

### ISSUE THREAD

**Issue by HenrikBengtsson** [twolodzko/kernelboot#2]
Hi, while running revdep checks on globals packages in single-core mode, I [got](https://github.com/HenrikBengtsson/globals/blob/revdep/wynton/revdep/problems.md#kernelboot):
```r
 ERROR
Running the tests in ‘tests/test_parallel.R’ failed.
Complete output:
  > 
  > library("kernelboot")
  > 
  > # simply check if it fails
  > 
  > stopifnot( kernelboot(mtcars, function(data) coef(lm(mpg ~ disp + hp + drat, data = data)),
  +                       R = 10, parallel = TRUE)$param$parallel )
  Error: kernelboot(mtcars, function(data) coef(lm(mpg ~ disp + hp + drat,  .... is not TRUE
  Execution halted
```

This is because [tests/test_parallel.R](https://github.com/twolodzko/kernelboot/blob/master/tests/test_parallel.R#L6-L7):
```r
stopifnot( kernelboot(mtcars, function(data) coef(lm(mpg ~ disp + hp + drat, data = data)),
R = 10, parallel = TRUE)$param$parallel )
```
assumes that `availableCores() > 1`. See also https://github.com/twolodzko/kernelboot/blob/master/R/kernelboot.R#L355-L368

**Comment by twolodzko** [comment]
Thanks, I'll fix that!

**Comment by twolodzko** [comment]
@HenrikBengtsson I don't know how could I test it on single-core setting, so could you please give me some hints, or confirm that now it the tests work fine?

**Comment by HenrikBengtsson** [comment]
If you set (parallel's) env var `MC_CORES` to a single core, then future will acknowledge that, e.g.
```sh
$ export MC_CORES=1
$ Rscript -e "future::availableCores()"
mc.cores 
       1
```
This should also work when you do:
```sh
$ export MC_CORES=1
$ R CMD check --as-cran kernelboot_x.y.z.tar.gz
```

**Comment by HenrikBengtsson** [comment]
Or, in your R test script, you can use:
```r
options(mc.cores = 1L)
```

**Comment by twolodzko** [comment]
@HenrikBengtsson thanks! I don't feel that this is urgent to update on CRAN, does it affect revdeps of your package?

**Comment by HenrikBengtsson** [comment]
Correct - nothing urgent, just though you might wanna know about it since the fix is simple.
